spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxy
    url: jdbc:mysql://localhost:3306/xxyftpserver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ftpserver:
  port: ${ftpport:2000}

